### ISSUE TITLE
Add ability to share selected category / maintenance plan

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/mashed#183]
1. Add ability to share selected category or maintenance plan between users.
2. Sharing plan gives users elevated privileges to the plan, or the user can set the plan down. 
3. We still need to discuss the capabilities of the user in this scenario.

**Comment by mohit2530** [comment]
From initial view, we might need a couple of things to be in place.

1. Api to support list of users.
2. Autocomplete component to search for user to share the modal with.
3. Since the lookup is done with sharable groups, users should be able to edit and view the respective groups. We might need to introduce RLS to support only by creator workflow, but that is not part of the discussion yet.
4. Allow free search and multiple values in autocomplete groups.
5. If the user is no longer available, it chip should be layered with a red hue or color to denote such instance.
6. If the user is unavailable, disable update / save button so that the users can rectify the mistake before proceeding.
