### ISSUE TITLE
Verify user age when sign up

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#29]
- Verify user signup when user sign up.
- This is a much more detailed process. we want to seperate the login and signup components on its own modular format.
- Sign up should display terms and service and privacy policy and other policies and usr must agree to them.
- We must store these values.
- We must make a history table on the login because we want all the login information and changes that the user makes.
- Add history table on the profile as well since we want to log the changes made by the user on his name.

**Comment by earmuff-jam** [comment]
Remaining - 

- Sign up should display terms and service and privacy policy and other policies and usr must agree to them.
- We must make a history table on the login because we want all the login information and changes that the user makes.
- Add history table on the profile as well since we want to log the changes made by the user on his name.
