### ISSUE TITLE
Update Add Item form to support more fields

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#75]
## Acceptance Criteria

1. Still WIP, but we need to add ticket prices and other features during creating an event. The existing modal that we use is still fine, we just need to add more fields to the selection screen. Sample of an example is attached but this is not final yet. we want to know what fields we have and what we need to add.
![image](https://github.com/earmuff-jam/mashed/assets/44540219/ca05e9d2-e913-4a8d-8057-f1d93e0e3b80)

**Comment by mohit2530** [comment]
These fields might also be required during update an event. Lets add them here as well if possible.

**Comment by earmuff-jam** [comment]
Missing fields in general are listed below.

1. SKU if fillable. If the user has a barcode or a sku that they would like to add, they should be able to. 
2. `Is the item returnable` boolean check allows for clients to know how many reusable stuffs they purchase.
3. If the above bullet is filled, it should be a checkbox with default value to false.
4. If selected true, we should display fields to add - `expiration date`
5. Add `min quantity` and `max quantity` to setup thresholds.
6. Weight -> unit of measurement, height -> unit of measurement, length -> unit of measurement, width -> unit of measurement
7. Cost price -> MSRP if possible as well. Selling high / low limits as well.
8. Allow users to draft this so that they can save and go edit it at a later date.
9. Save all items in redux we need users to come back to prefilled values if possible.

**Comment by mohit2530** [comment]
Branch associated `add-extra-item-fields`

**Comment by mohit2530** [comment]
Added a couple of fields to support adding a new item.
